services:
  - type: web
    name: infinitbiz
    env: docker
    dockerfilePath: ./Dockerfile
    plan: starter
    region: ohio
    branch: main
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: infinitetechai
          property: connectionString
      - key: PORT
        value: 10000
      - key: PYTHON_VERSION
        value: 3.11.0
